services:

    db:
      image: postgres:16.2
      restart: always
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    web:
      build: .
      command:  python /code/manage.py runserver localhost:8000

      restart: always
      volumes:
        - .:/code
      ports:
        - "8080:8000"
      environment:
        - DJANGO_SETTINGS_MODULE=Metamarket.settings.prod
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      
      depends_on:
        - db

  