
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: Metamarket.settings.prod
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: python /code/manage.py migrate

  web_run:
    extends:
      service: web
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - web_migrate

  cache:
    image: redis:7.2.4
    restart: always
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DB}
    volumes:
      - ./data/cache:/data
