services:
  db:
    image: postgres:16.2
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
  
  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/build
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on:
      - db
      - cache
