services:

    web:
      build: .
      command:  python /code/manage.py runserver localhost:8000

      restart: always
      volumes:
      - .:/code
      ports:
      - "8080:8000"
      environment:
      - DJANGO_SETTINGS_MODULE=Metamarket.settings.prod

    