
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: Metamarket.settings.prod
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "/code/manage.py", "migrate"]

  web_run:
    extends:
      service: web
    command: ["./wait-for-it.sh", 
              "db:5432", 
              "--",
              "python",
               "/code/manage.py",
                "runserver",
                "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - web_migrate
      - db
  db:
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  cache:
    image: redis:7.2.4
    restart: always
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DB}
    volumes:
      - ./data/cache:/data
