# Generated by Django 5.1.1 on 2024-11-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='date_from',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='date_to',
            new_name='valid_to',
        ),
    ]
