# Generated by Django 5.1.1 on 2024-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_date_from_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
