# Generated by Django 5.1.1 on 2024-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_rename_amount_coupon_amount_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
